name: ohnho
favicon: null
layout_spectrum: 0.03692420176230371
typography_spectrum: 0.7129585084039718
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7759769419208169
  lightness: 0.5069750072434545
  saturation: 0.1388621141668409
  rhythmicContrast: 0.4384245425462723
purpose: []
